import Link from "next/link";

export default function NotFound() {
  return (
    <main className="mx-auto flex min-h-full w-full max-w-md flex-1 flex-col justify-center px-6 py-20">
      <h1 className="text-lg font-semibold tracking-tight text-stone-900">
        That workspace link isn&apos;t valid
      </h1>
      <p className="mt-2 text-sm leading-relaxed text-stone-600">
        Workspace links are generated by the app and can&apos;t be typed from
        memory. If you had one, check it was copied in full.
      </p>
      <Link
        href="/"
        className="mt-6 self-start rounded-md bg-stone-900 px-3.5 py-2 text-sm font-medium text-white transition hover:bg-stone-700"
      >
        Start a new workspace
      </Link>
    </main>
  );
}
